POST https://wl2api.herokuapp.com/client/register
Content-Type: application/json

{
    "name": "hawn",
    "surname": "uiwiksak",
    "email": "radeejk@jsja.com",
    "address": "inputs[3].value",
    "coordinates": [334,556],
    "password": "inputs[6].value",
    "cell":"inputs[7].value"
}

###

GET https://wl2api.herokuapp.com/experts
